################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
services:
  hasher:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    image: academiaonline/dockercoins:latest-hasher
    networks:
    - hasher
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    image: redis:latest
    networks:
    - redis
    volumes:
    - redis:/data
  rng:
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    image: academiaonline/dockercoins:latest-rng
    networks:
    - rng
  webui:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    image: academiaonline/dockercoins:latest-webui
    networks:
    - redis
    ports:
    - 30000:8080
  worker:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    image: academiaonline/dockercoins:latest-worker
    networks:
    - hasher
    - redis
    - rng
version: '3.8'
volumes:
  redis:
