################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
services:
  hasher:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 100m
        reservations:
          cpus: "0.4"
          memory: 100m
    image: academiaonline/dockercoins:2.0-hasher
    networks:
    - hasher
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 100m
        reservations:
          cpus: "0.4"
          memory: 100m
    image: redis:6.0.9-alpine3.12@sha256:aa31e6d2afc72d2222ed3953587197c324f615861771637a64053f9d99ba4b74
    networks:
    - redis
    volumes:
    - redis:/data
  rng:
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
      resources:
        limits:
          cpus: "0.4"
          memory: 100m
        reservations:
          cpus: "0.4"
          memory: 100m
    image: academiaonline/dockercoins:2.0-rng
    networks:
    - rng
  webui:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 1g
        reservations:
          cpus: "0.4"
          memory: 1g
    image: academiaonline/dockercoins:2.0-webui
    networks:
    - redis
    ports:
    - 30000:8080
  worker:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 100m
        reservations:
          cpus: "0.4"
          memory: 100m
    image: academiaonline/dockercoins:2.0-worker
    networks:
    - hasher
    - redis
    - rng
version: '3.8'
volumes:
  redis:
